# DISPLAY
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FPS = 60
RENDER_FPS = 60
BG_COLOR = (15, 15, 20)

# AGENT
AGENT_RADIUS = 10
AGENT_COLOR = (0, 200, 255)
AGENT_SPEED = 2.0
AGENT_TURN_RATE = 3  # Degrees/Frame
AGENT_MAX_SPEED = 5.0

# FOOD
FOOD_COLOR = (0, 255, 100)
FOOD_RADIUS = 5
MAX_FOOD = 25
FOOD_RESPAWN_THRESHOLD = 8
FOOD_RESPAWN_RATE = 0.5
FOOD_RESPAWN_INTERVAL = int(1 / FOOD_RESPAWN_RATE * FPS)

# NEST
NEST_COLOR = (255, 255, 0)  # Yellow
NEST_RADIUS = 25
NEST_POSITION = (int(0.9 * SCREEN_WIDTH), int(0.88 * SCREEN_HEIGHT))

# REWARDS
REWARD_WALL_COLLISION = -0.5 # Increased from -0.1
REWARD_AGENT_COLLISION = -0.25  # Reduced from -0.5 (less harsh on cooperation)
REWARD_FOOD_PICKUP = +5.0
REWARD_FOOD_DEPOSIT = +10.0
REWARD_STEP = -0.01  # Increased from -0.001 (10x stronger efficiency pressure)

# ---------- RAYCAST / SENSORS ----------
NUM_RAYS = 5
RAY_SPAN_DEG = 90
RAY_MAX_DIST = 120
RAY_STEP = 6

# ---------- HUD / DEBUG ----------
HUD_PADDING = 8
HUD_TEXT_COLOR = (230, 230, 230)
FONT_SIZE = 14

# ---------- TRAINING ----------
TOTAL_TIMESTEPS = 1_000_000
CHECKPOINT_FREQ = 10_000
LOG_DIR = "./logs/"
MODEL_DIR = "./models/"
